persistence:
  enabled: false #TODO change to true
  size: 1Gi
  accessMode: ReadWriteOnce

images:
  pullSecret: 
  flavour: main

ingressroute:
  baseHost: dapetri.com

frontend:
  image:
    name: ghcr.io/dapetri/dafolio
    tag: 0.1.7
  secrets: []
  configs: []

backend:
  image:
    name: ghcr.io/dapetri/dafolio-backend
    tag: 0.1.0
  secrets: 
  - backend-secrets
  configs: []

postgres:
  image:
    name: postgres
    tag: 12.2-alpine
  secrets:
  - postgres-secrets
  configs: []