persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

images:
  pullSecret: 
  flavour: main

dafolio:
  image:
    name: ghcr.io/dapetri/dafolio
    tag: 0.1.2
  secrets: []
  configs: []