persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

images:
  pullSecret: 
  flavour: main

ingressroute:
  baseHost: dev.dapetri.com

dafolio:
  image:
    name: ghcr.io/dapetri/dafolio
    tag: 0.1.4
  secrets: []
  configs: []