persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

images:
  pullSecret: 
  flavour: main

ingressroute:
  baseHost: dapetri.com

frontend:
  image:
    name: ghcr.io/dapetri/dafolio
    tag: 0.1.6
  secrets: 
  - dafolio-frontend-secrets
  configs: []