{{- with .Values.dafolio }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dafolio.fullname" $ }}-dafolio
spec:
  selector:
    matchLabels:
        {{- include "dafolio.matchLabels" $ | nindent 8 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "dafolio.labels" $ | nindent 8 }}
        app.kubernetes.io/component: dafolio
    spec:
      containers:
      - name: dafolio
        image: {{ include "dafolio.generateFlavourImage" (dict "image" .image) }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        {{- if gt (add (len .secrets) (len .configs)) 0 }}
        envFrom:
        {{- range .secrets }}
        - secretRef:
            name: {{ . | quote }}
        {{- end }}
        {{- range .configs }}
        - configMapRef:
            name: {{ . | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 200m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dafolio.fullname" $ }}-dafolio
spec:
  selector:
    app.kubernetes.io/name: {{ include "dafolio.name" $ }}
    app.kubernetes.io/component: dafolio
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
{{- end }}