apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "dafolio.fullname" $ }}-ingress
  labels:
    {{- include "dafolio.labels" $ | nindent 4 }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.baseHost }}`) || Host(`www.{{ .Values.ingressroute.baseHost }}`)
    services:
    - name: {{ include "dafolio.fullname" $ }}-frontend
      port: 80
    priority: 10
  tls:
    certResolver: cloudflare
