{{- with .Values.persistence }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dafolio.fullname" $ }}-db-lh
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "dafolio.labels" $ | nindent 4 }}
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/low-prio: enabled
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .storageClass }}
  storageClassName: longhorn-crypto-global
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
{{- end }}
{{- end }}